name: SID_UNet_Baseline
model_type: ImageRestorationModel
scale: 1
manual_seed: 42

datasets:
  train:
    name: SID-train
    type: SonySIDLMDBDataset
    phase: train
    manifest_path: /content/drive/MyDrive/Lowlight/SID/manifest_sid.json
    subset: train
    patch_size: 512
    samples_per_pair: 4
    random_crop: true
    batch_size_per_gpu: 4
    num_worker_per_gpu: 4
    pin_memory: true
    prefetch_mode: cuda
    io_backend:
      type: lmdb
      db_paths:
        - /content/drive/MyDrive/Lowlight/SID/lmdb/train_short.lmdb
        - /content/drive/MyDrive/Lowlight/SID/lmdb/train_long.lmdb
      client_keys:
        - short
        - long
  val:
    name: SID-val
    type: SonySIDLMDBDataset
    phase: val
    manifest_path: /content/drive/MyDrive/Lowlight/SID/manifest_sid.json
    subset: val
    random_crop: false
    samples_per_pair: 1
    batch_size_per_gpu: 1
    num_worker_per_gpu: 1
    pin_memory: false
    io_backend:
      type: lmdb
      db_paths:
        - /content/drive/MyDrive/Lowlight/SID/lmdb/val_short.lmdb
        - /content/drive/MyDrive/Lowlight/SID/lmdb/val_long.lmdb
      client_keys:
        - short
        - long

network_g:
  type: UNetSIDModel
  in_channels: 3
  out_channels: 3
  base_channels: 32
  bilinear: true

path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

train:
  total_iter: 300000
  warmup_iter: -1
  optim_g:
    type: Adam
    lr: 1.0e-4
    betas: [0.9, 0.999]
  scheduler:
    type: MultiStepLR
    milestones: [100000, 200000]
    gamma: 0.5
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean
  use_grad_clip: true

val:
  val_freq: 5000
  save_img: false
  use_image: false
  metrics:
    psnr_linear:
      type: linear_psnr
      data_range: 1.0
    ssim_linear:
      type: linear_ssim
      data_range: 1.0
    lpips_vgg:
      type: lpips_distance
      net: vgg
    deltaE_mean:
      type: deltae2000_mean
    deltaE_edge:
      type: edge_deltae2000_mean

logger:
  print_freq: 100
  save_checkpoint_freq: 5000
  use_tb_logger: true

dist_params:
  backend: nccl
